spring.datasource.url=jdbc:h2:file:~/home/ubuntu/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#enabling the H2 console
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update

server.port=9000

eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true
eureka.client.service-url.defaultZone = http://localhost:8502/eureka
eureka.instance.hostname = localhost

spring.application.name = teacher-service

spring.main.web-application-type=reactive
