FROM openjdk:11

LABEL mentainer="tamilmani.kumarasamy@ideas2it.com"

WORKDIR /app

COPY /target/student-0.0.1-SNAPSHOT.jar /app/student-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "springboot-docker-demo.jar"]
