server:
  port: 8400

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8502/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: student-service
          uri:  lb://student-service
          predicates:
            - Path=/api/v1/students/**
        - id: teacher-service
          uri:  lb://teacher-service
          predicates:
            - Path=/api/v1/teachers/**
