server.port=8500
spring.application.name=common-service

eureka.client.registerWithEureka = true
eureka.client.fetchRegistry = true

eureka.client.service-url.defaultZone = http://localhost:8502/eureka
eureka.instance.hostname = localhost

spring.main.web-application-type=reactive
